import type { Metadata } from "next";
import { Chakra_Petch, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import tokens from "../../tokens.json";
import { AUTHOR_NAME, AUTHOR_URL, createPageMetadata, SITE_ORIGIN } from "./authority";

const chakra = Chakra_Petch({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-chakra",
  display: "swap"
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-jetbrains",
  display: "swap"
});

export const metadata: Metadata = {
  ...createPageMetadata({
    path: "/",
    title: "Jeremy Joseph Curry - Software Engineer & App Developer in Nepal",
    description:
      "Jeremy Joseph Curry is a software engineer and independent app developer based in Nepal, building mobile apps, web applications, websites, backend systems, and AI-powered software.",
    type: "website"
  }),
  metadataBase: new URL(SITE_ORIGIN),
  authors: [{ name: AUTHOR_NAME, url: AUTHOR_URL }],
  keywords: [
    "Jeremy Joseph Curry",
    "Jeremy Curry",
    "software engineer Nepal",
    "app developer Nepal",
    "full-stack developer",
    "mobile app developer",
    "web developer",
    "AI software developer",
    "Bible Trivia Quest",
    "HimalRx",
    "GPTrek",
    "Green Pastures Adventures",
    "Gurkha Fit"
  ],
  icons: {
    icon: "/favicon.svg"
  }
};

// Design tokens (colors, fonts) come from tokens.json — generated by
// `blueprint tokens <slug>` from the donor, or the template default. We inject them
// as :root CSS custom properties so the whole site reads from one source of truth
// and changing a token value visibly changes the render.
function tokenCssVars(): string {
  const c = tokens.colors;
  const f = tokens.fonts;
  return `:root{--color-background:${c.background};--color-foreground:${c.foreground};--color-primary:${c.primary};--color-accent:${c.accent};--color-muted:${c.muted};--font-heading:${f.heading.stack};--font-body:${f.body.stack};}`;
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${chakra.variable} ${jetbrains.variable}`}>
      <head>
        <style dangerouslySetInnerHTML={{ __html: tokenCssVars() }} />
      </head>
      <body>{children}</body>
    </html>
  );
}
