import type {
  CatalogueCategory,
  CatalogueProduct,
  NavGroup,
  RouteRecord,
} from "./types.ts";

export const referenceCategories: CatalogueCategory[] = [
  { slug: "coffee", name: "Coffee" },
  { slug: "tea", name: "Tea" },
  { slug: "chocolate", name: "Chocolate" },
  { slug: "merchandise", name: "Merchandise" },
];

export const referenceProducts: CatalogueProduct[] = [
  {
    slug: "decaf-ethiopia-suke-quto",
    name: "Decaf Ethiopia Suke Quto",
    category: "coffee",
    description: "Reference-only donor product used to prove the product-detail template.",
    media: {
      src: "/reference-only/decaf-ethiopia-suke-quto.webp",
      alt: "Onyx reference coffee package",
      provenance: "reference-only",
    },
  },
  {
    slug: "colombia-la-riviera-sudan-rume",
    name: "Colombia La Riviera Sudan Rume",
    category: "coffee",
    media: {
      src: "/reference-only/colombia-la-riviera.webp",
      alt: "Onyx reference coffee package",
      provenance: "reference-only",
    },
    tastingNotes: ["Floral", "Stone fruit", "Cacao"],
  },
  {
    slug: "cafe-expressions",
    name: "Cafe Expressions",
    category: "coffee",
    media: {
      src: "/reference-only/cafe-expressions.webp",
      alt: "Onyx reference bottled beverage",
      provenance: "reference-only",
    },
  },
  {
    slug: "specialty-matcha",
    name: "Specialty Matcha",
    category: "tea",
    media: {
      src: "/reference-only/specialty-matcha.webp",
      alt: "Onyx reference matcha product",
      provenance: "reference-only",
    },
  },
  {
    slug: "sipping-chocolate",
    name: "Sipping Chocolate",
    category: "chocolate",
    media: {
      src: "/reference-only/sipping-chocolate.webp",
      alt: "Onyx reference sipping chocolate",
      provenance: "reference-only",
    },
  },
];

export const referenceRoutes: RouteRecord[] = [
  { path: "/", title: "Skip to content", family: "home" },
  { path: "/account/login", title: "Login", family: "account" },
  { path: "/cart", title: "0", family: "cart" },
  { path: "/collections/accessories", title: "Accessories", family: "collection" },
  { path: "/collections/all-merch", title: "All Merch", family: "collection" },
  { path: "/collections/apparel", title: "Apparel", family: "collection" },
  { path: "/collections/barista-provisions", title: "Barista Provisions", family: "collection" },
  { path: "/collections/chocolate-covered", title: "Chocolate Covered", family: "collection" },
  { path: "/collections/coffee", title: "Coffee", family: "collection" },
  { path: "/collections/coffee-archive", title: "Archive", family: "collection" },
  { path: "/collections/collaborations", title: "Collaborations", family: "collection" },
  { path: "/collections/colombia-coffees", title: "Colombia Known for innovation and resilience, Colombia's coffee history dates...", family: "collection" },
  { path: "/collections/cometeer", title: "Cometeer", family: "collection" },
  { path: "/collections/doyenne", title: "Doyenne", family: "collection" },
  { path: "/collections/drinkware", title: "Drinkware", family: "collection" },
  { path: "/collections/ecuador-coffees", title: "Ecuador Ecuador’s coffee production is shaped by its incredible biodiversity,...", family: "collection" },
  { path: "/collections/equipment", title: "Equipment", family: "collection" },
  { path: "/collections/gift-subscriptions", title: "Subscriptions", family: "collection" },
  { path: "/collections/instant-coffee", title: "Specialty Instant", family: "collection" },
  { path: "/collections/matcha", title: "Matcha", family: "collection" },
  { path: "/collections/peru-coffees", title: "Peru Peru offers some of the best offerings for us to enjoy. Known for care a...", family: "collection" },
  { path: "/collections/red", title: "Explore (ONYX)RED", family: "collection" },
  { path: "/collections/special", title: "Box Sets", family: "collection" },
  { path: "/collections/tea", title: "Tea", family: "collection" },
  { path: "/collections/tea-box-sets", title: "Box Sets", family: "collection" },
  { path: "/collections/terroir", title: "Chocolate", family: "collection" },
  { path: "/collections/traditional-bars", title: "Traditional Bars", family: "collection" },
  { path: "/pages/bentonville", title: "Bentonville", family: "editorial" },
  { path: "/pages/brew-guides", title: "Brew Guides", family: "editorial" },
  { path: "/pages/doyenne-cafe", title: "Doyenne", family: "editorial" },
  { path: "/pages/equipment-repair", title: "Espresso Repair", family: "editorial" },
  { path: "/pages/faq", title: "FAQ", family: "editorial" },
  { path: "/pages/fay-square", title: "Fay Square", family: "editorial" },
  { path: "/pages/fayetteville", title: "Gregg St", family: "editorial" },
  { path: "/pages/find-my-roast", title: "Find My Roast", family: "editorial" },
  { path: "/pages/grind-size-calculator", title: "Grind Sizes", family: "editorial" },
  { path: "/pages/help-me-brew", title: "Help Me Brew", family: "editorial" },
  { path: "/pages/help-me-choose", title: "Help Me Choose", family: "editorial" },
  { path: "/pages/jobs", title: "Careers", family: "editorial" },
  { path: "/pages/locations", title: "See Our Cafes", family: "editorial" },
  { path: "/pages/our-story", title: "Awards", family: "editorial" },
  { path: "/pages/privacy", title: "Privacy Statement", family: "policy" },
  { path: "/pages/private-events", title: "Private Events", family: "editorial" },
  { path: "/pages/quick-order", title: "In a hurry?", family: "editorial" },
  { path: "/pages/rogers", title: "Rogers", family: "editorial" },
  { path: "/pages/springdale", title: "Springdale", family: "editorial" },
  { path: "/pages/subscribe", title: "Subscriptions", family: "editorial" },
  { path: "/pages/subscribe-tea", title: "Tea", family: "editorial" },
  { path: "/pages/support", title: "Help Center", family: "editorial" },
  { path: "/pages/terms", title: "Terms & Conditions", family: "policy" },
  { path: "/pages/the-momentary", title: "Momentary", family: "editorial" },
  { path: "/pages/wholesale", title: "Wholesale", family: "editorial" },
  { path: "/policies/privacy-policy", title: "Privacy Policy", family: "policy" },
  { path: "/policies/terms-of-service", title: "Terms of Use", family: "policy" },
  { path: "/products/cafe-expressions", title: "Cafe Expressions", family: "product" },
  { path: "/products/circadian", title: "Circadian", family: "product" },
  { path: "/products/colombia-la-riviera-sudan-rume-26", title: "Explore The Offering", family: "product" },
  { path: "/products/decaf-ethiopia-suke-quto-26", title: "Explore This Offering", family: "product" },
  { path: "/products/echelon", title: "Echelon", family: "product" },
  { path: "/products/echelon-2025", title: "Echelon 2026", family: "product" },
  { path: "/products/gift-card", title: "Gift Cards", family: "product" },
  { path: "/products/roasters-choice", title: "Roaster's Choice", family: "product" },
  { path: "/products/sipping-chocolate-powder", title: "Sipping Chocolate", family: "product" },
  { path: "/products/usa-cycling", title: "EXPLORE THE COLLAB", family: "product" },
];

export const referenceNavigation: NavGroup[] = [
  {
    label: "Shop",
    items: [
      { label: "Coffee", href: "/collections/coffee" },
      { label: "Tea", href: "/collections/tea" },
      { label: "Chocolate", href: "/collections/terroir" },
      { label: "Merchandise", href: "/collections/all-merch" },
    ],
  },
  {
    label: "Experience",
    items: [
      { label: "Our Story", href: "/pages/our-story" },
      { label: "Locations", href: "/pages/locations" },
      { label: "Help Center", href: "/pages/support" },
      { label: "Quick Order", href: "/pages/quick-order" },
    ],
  },
];
