import type { Metadata } from "next";
import "./globals.css";
import tokens from "../../tokens.json";
import { Footer } from "@/components/chrome/Footer";
import { Header } from "@/components/chrome/Header";
import { RevealController } from "@/components/motion/RevealController";

export const metadata: Metadata = {
  title: "Ambika Juice — Fresh Juice in Pokhara",
  description: "Fresh juices, smoothies, lassi, milkshakes and fruit salads at Rastra Bank Chowk, Pokhara."
};

// Design tokens (colors, fonts) come from tokens.json — generated by
// `blueprint tokens <slug>` from the donor, or the template default. We inject them
// as :root CSS custom properties so the whole site reads from one source of truth
// and changing a token value visibly changes the render.
function tokenCssVars(): string {
  const c = tokens.colors;
  const f = tokens.fonts;
  return `:root{--color-background:${c.background};--color-foreground:${c.foreground};--color-primary:${c.primary};--color-accent:${c.accent};--color-muted:${c.muted};--font-heading:${f.heading.stack};--font-body:${f.body.stack};}`;
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style dangerouslySetInnerHTML={{ __html: tokenCssVars() }} />
      </head>
      <body>
        <RevealController />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
